### ISSUE TITLE
Greek Translation

### ISSUE THREAD

**Issue by groubis** [alterebro/beaufort-scale#1]
Hello and thanks for your nice script,

if you want to add Greek translation, this is the array of objects including Greek:

`  var s = [
      { speed: 0, desc: { en: "Calm", es: "Calma", el: "Άπνοια" } },
      { speed: 2, desc: { en: "Light air", es: "Ventolina",el :"Σχεδόν άπνοια" } },
      { speed: 6, desc: { en: "Light breeze", es: "Brisa muy débil",el :"Πολύ ασθενής" } },
      { speed: 12, desc: { en: "Gentle breeze", es: "Brisa ligera",el :"Ασθενής" } },
      { speed: 20, desc: { en: "Moderate breeze", es: "Brisa moderada",el :"Σχεδόν μέτριος" } },
      { speed: 29, desc: { en: "Fresh breeze", es: "Brisa fresca",el :"Μέτριος" } },
      { speed: 39, desc: { en: "Strong breeze", es: "Brisa fuerte",el :"Ισχυρός" } },
      { speed: 50, desc: { en: "High wind", es: "Viento fuerte",el :"Σχεδόν θυελλώδης" } },
      { speed: 62, desc: { en: "Gale", es: "Temporal",el :"Θυελλώδης" } },
      { speed: 75, desc: { en: "Strong gale", es: "Temporal fuerte", el: "Πολύ θυελλώδης" } },
      { speed: 89, desc: { en: "Storm", es: "Temporal duro", el : "Θύελλα"  } },
      { speed: 103, desc: { en: "Violent Storm", es: "Borrasca", el : "Σφοδρή θύελλα" } },
      { speed: 118, desc: { en: "Hurricane", es: "Huracán", el : "Τυφώνας" } }
    ]`

Thanks,

**Comment by alterebro** [comment]
Thanks @groubis! It won't be added to the source in order to keep the script lightweight but I'm definitely going to look about how to include it. As a parameter I guess...
Cheers,
Jorge.

**Comment by alterebro** [comment]
Ok, this is fixed now to allow a language array of strings as a parameter, thanks!
